FROM golang:1.8
LABEL maintainer="Chris Collins <collins.christopher@gmail.com>"

ENV appname=gorestapp

ENV appdir=/go/src/github.com/clcollins/gorestapp

ENV CGO_ENABLED=0
ENV GOOS=linux

COPY ./ ${appdir}
WORKDIR ${appdir}

RUN go get
RUN go build -o /build/${appname} -a -installsuffix cgo -v

RUN go test -v
